version: '3.8'

services:
  service-a:
    build:
      context: ./service-a
    container_name: service-a
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=service-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - SERVICE_B_URL=http://service-b:8081
    depends_on:
      - otel-collector

  service-b:
    build:
      context: ./service-b
    container_name: service-b
    ports:
      - "8081:8081"
    environment:
      - SERVICE_NAME=service-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - WEATHER_API_KEY=dd69660279c7451593102923261505
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
